name: Build, Test, and Deploy PipesAndFilters
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: build
        run: |
          cd src
          dotnet restore
          dotnet build --configuration Release --no-restore
      - name: test
        run: |
          cd src
          dotnet test --no-restore --verbosity normal
      - name: publish
        run: |
          cd src
          dotnet nuget push PipesAndFilters/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s $SOURCE_URL
        env:
          SOURCE_URL: https://api.nuget.org/v3/index.json
          NUGET_AUTH_TOKEN:  ${{secrets.NUGET_AUTH_TOKEN}}
