name: Build and Test Solution

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: build
        run: |
          cd src
          dotnet restore
          dotnet build --configuration Release --no-restore
      - name: test
        run: |
          cd src
          dotnet test --no-restore --verbosity normal
