name: .NET Core

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout repository
        uses: actions/checkout@master
    
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
          
      - name:  Navigate to source
        run: cd src
    
      - name: Install dependencies
        run: dotnet restore
    
      - name: Build
        run: dotnet build --configuration Release --no-restore
    
      - name: Test
        run: dotnet test --no-restore --verbosity normal
